### PR TITLE
Fix #51 - Tests fail on non Linux/Unix platforms

### LINKED ISSUE #51: Tests fail due to non-cross platform separators.
Hi, building `fu` fails with
```java
org.opentest4j.AssertionFailedError: expected: </tmp/mylog.txt> but was: <C:\tmp\mylog.txt>
```

### PR DESCRIPTION
**Pull request by AlexCzar**
This failure was caused because code assumes specific filesystem layout, which in actuality differs on different platforms and sometimes even within a platform based on security policy.
This PR (hopefully) fixes the problem by introducing platform/policy-independent way to create temporary files needed for tests.
This is my first PR, so I'll be grateful for any feedback and suggestions.
PS: I've signed the CLA

### CODE REVIEW

File: modules/logging/src/test/kotlin/org/springframework/fu/module/logging/LogbackDslTest.kt [hunk 1]
```diff
@@ -32,6 +32,9 @@ import java.io.File
 /**
  * @author Thomas Girard
  */
+
+private val TMP = System.getProperty("java.io.tmpdir").let(::File)
```
Comment (sdeleuze) [inline modules/logging/src/test/kotlin/org/springframework/fu/module/logging/LogbackDslTest.kt]: I think I would prefer a `private val tmpdir: File` property in`LogbackDslTest` (test classes are instantiated just a single time).

**Comment by sdeleuze** [comment]
Thanks for your contribution.
